ES_PORT: 9201
ES_INDEX: "drugs"

NEO4J_URI: "neo4j+s://e7958ee4.databases.neo4j.io:7687"
NEO4J_USER: "neo4j"
NEO4J_PSW: "PefqeKG_6KZPCGLC-VYFuEH4RTr_HzgDX6aNWPnKQa8"

INTERACTION_API_IP: "localhost"
INTERACTION_API_PORT: 5163

MAIN_IP: "127.0.0.1"
MAIN_PORT: 8002