ES_PORT: 9200
ES_INDEX: "drugs"

NEO4J_URI: "bolt://localhost:7687"
NEO4J_USER: "neo4j"
NEO4J_PSW: "password"

INTERACTION_API_IP: "localhost"
INTERACTION_API_PORT: 5163

MAIN_IP: "127.0.0.1"
MAIN_PORT: 8003