version: '3.7'

# The different services that make up our "network" of containers
services:
    ## Defining the Neo4j Database Service
    neo:
        # The image to use
        image: neo4j:latest
        # map the ports, so we can check the db server is up
        ports:
            - 7474:7474
            - 7687:7687
        # mounting a named volume to the container to track db data
        volumes:
            - neo4j_data:/data/
        env_file:
            - .env.neo4j

## volumes to be generated, these are saved somewhere for repeated use by docker
volumes:
    neo4j_data: